version: '3'

services:
  ###> PHP-FPM ###
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - database

  ###> NGINX ###
  nginx:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  ###> MySQL ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-auren}
      MYSQL_USER: ${MYSQL_USER:-jojopok}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wild}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - database_data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###

volumes:
  database_data:
